# Generated by Django 4.1.10 on 2023-09-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbuilder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table1', models.CharField(max_length=255)),
                ('table2', models.CharField(max_length=255)),
                ('relationship_type', models.CharField(max_length=10)),
            ],
        ),
    ]
