# Generated by Django 4.1.10 on 2023-08-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbuilder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
