# Generated by Django 4.1.10 on 2023-08-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbuilder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=100)),
                ('field2', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Imported Tables',
            },
        ),
    ]
