# Generated by Django 4.1.10 on 2023-08-23 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appbuilder', '0002_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('from_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_relationships', to='appbuilder.uploadedfile')),
                ('to_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_relationships', to='appbuilder.uploadedfile')),
            ],
        ),
    ]
