# Generated by Django 4.1.10 on 2023-09-05 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbuilder', '0003_dynamictable_dynamictablecolumn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamictable',
            name='primary_key',
        ),
        migrations.DeleteModel(
            name='DynamicTableColumn',
        ),
    ]
