# Generated by Django 4.1.10 on 2023-08-24 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbuilder', '0003_relationship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
